services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poca-service-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      bash -c "python init_db.py --force && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
